### PR TITLE
Firefox extension : converting the LiveReload’s status icon to a toolbar button.

### PR DESCRIPTION
**Pull request by bergalath**
Here are the few changes to make this button movable from the Firefox’s palette toolbar.
I have made them for a while now, but never took time to push them.
So I decided to do it as soon as I saw the issue #85 from @pjg.

If you can’t wait for the new version to be available on Mozilla’s add-ons site, just apply these changes directly to your installed extension or rebuild it with the `rake firefox` task from your repo directory.
It works well for me with Guard.

Hope it helps and it could be usefull ;o)
(sorry I’m too low on battery to find if it’s possible to link this pull-request with the #85 issue directly ??!!?!)

### CODE REVIEW

**Comment by NV** [comment]
Thank you for the patch!

screenshot

LR button looks unnaturally near the others. Can you add a "button style"?

> (sorry I’m too low on battery to find if it’s possible to link this pull-request with the #85 issue directly ??!!?!)

Unfortunately, GitHub doesn't have UI for that.

**Comment by pjg** [comment]
Cool! Yeah, some better styling could be helpful too :)

**Comment by bergalath** [comment]
Oh well, I’m a bit confused about styling since my Firefox theme does not draw buttons’ borders as you can see :
livereload_screenshot

So, I’ll try to deal with that later on.
Stay tuned ;o)

**Comment by bergalath** [comment]
With those attributes, now the button should look like others, depending on your theme … at last I hope so !!

**Comment by pjg** [comment]
Thanks @bergalath !

**Pull request merged**
