### PR TITLE
Works on file://* in Chrome

### PR DESCRIPTION
**Pull request by NV**
Currently, neither the Chrome extensions nor the Safari extension work on `file://`. I dunno about Safari, but I fixed it for the Chrome extension.

file scheme  
_You have to check this checkbox_

By the way, it's not easy to publish an extension with file permissions. You have to go through a manual review and then sight some paper (they will send email, you'll have to print it), then scan it, and then mail it back (or fax it, lol).

### CODE REVIEW

**Comment by NV** [comment]
I was wrong! There is no need for the review anymore! I just published my [Chrome-o-Tile](http://github.com/NV/chrome-o-tile/) extension, which using `"matches": ["<all_urls>"]` and it works well! `<all_urls>` is a new [match pattern](http://code.google.com/chrome/extensions/match_patterns.html). I suppose, `file://*/*` also does not require the review anymore.

**Comment by dottedmag** [comment]
Oh, nice. Will be done in next upload then.

**Comment by NV** [comment]
Landed in 6f74f3146ca9b6bc0a639edda2c76250580215c8.

**Comment by henrikr** [comment]
Is there any update for the Safari Extension? Or will I have to switch over to Chrome to work on local files?

The server returns "Browser URL: undefined" but monitors all the files being modified.

EDIT: Thanks @NV, will switch over to Chrome for local files.

**Comment by NV** [comment]
There is no update for the Safari extension. Safari extensions do not allowed to run on local files.

**Comment by NV** [comment]
LiveReload 1.5 Chrome extension and Safari extension have been released.
Closed by 38532bd8a0b3c556ef72d84d47fec1c3a6fd4d7a
Closed by 38532bd8a0b3c556ef72d84d47fec1c3a6fd4d7a
Closed by 38532bd8a0b3c556ef72d84d47fec1c3a6fd4d7a

**Pull request closed without merging**
