### PR TITLE
Playframework SASS module support

### PR DESCRIPTION
**Pull request by tonyxiao**
Added two lines to allow livereload to live reload changes from scss and ass files generated by playframework's sass module (http://www.playframework.org/modules/sass)
- These two modules compiles the .sass and .scss files on the fly before sending valid vanilla css out to the browser. However the extensions used in html files to include those _special_ css files are sass and scss. 

If there is no conflict this could be an interesting addition to people using playframework

### CODE REVIEW

**Comment by NV** [comment]
I don't quite understand the purpose of this change. Does browser still receive a plain CSS?

**Comment by tonyxiao** [comment]
Yea, browser still gets plain CSS . Server set up to compile scss
before serving, just with different file extension

Tony Xiao
Vision without execution is delusion.

On Mar 29, 2011, at 7:11 AM, NV
reply@reply.github.com
wrote:

**Comment by NV** [comment]
I get it now.

You edit some.scss file and LiveReload tells to the browser what "some.scss" is changed. Before your patch, LiveReload would reload the whole page. With your patch LiveReload reloads all stylesheets because "some**.scss**" won't match with "some**.css**".

Correct me if I'm wrong.

**Comment by tonyxiao** [comment]
Yep exactly. I could be wrong, but I think whenever you include .scss and .sass files as stylesheet links directly in html pages, it is implicit that the files are processed and parsed by the server before sending valid css, instead of SASS to the browsers. 

That said this could be a rather specific feature of some web app frameworks / plugins, if you plan to keep livereload 100% "pure", it might make sense to leave things like this out. Though I'm not aware of any kind of conflicts with any other frameworks etc. as of now

**Comment by NV** [comment]
Merged 10 days ago. Closing.

**Pull request closed without merging**
