### PR TITLE
Firefox extension: options dialog

### PR DESCRIPTION
**Pull request by justmoon**
Adds a simple options dialog to the Firefox extension for setting host and port.

### CODE REVIEW

**Comment by NV** [comment]
How can I invoke options dialog? Can't find any clue on add-ons page in latest Minefield.

**Comment by justmoon** [comment]
The `optionsUrl` causes Firefox to display an Options button in the Addon Manager.

Here is a screenshot.
http://i.imgur.com/W7iaR.jpg

Tested in Firefox 4 RC, no idea why it wouldn't show up in Minefield.

**Comment by NV** [comment]
Everything works fine. I was testing wrong revision.

**Comment by NV** [comment]
Shipped in 0.6.1 https://addons.mozilla.org/firefox/addon/livereload/

**Pull request closed without merging**
